model_cache_path: '../ckpt' # Path to cache models
num_workers: 2
dependencies: [image]

data:
  image:
    meta_data_path: "demos/image_eval/image.json"
    data_path: "demos/image_eval/images"
    ref_meta_data_path: "demos/image_eval/image.json" # just for convenience
    ref_data_path: "demos/image_eval/images"
    image_key: 'image'
    formatter: 'GenImageFormatter'

scorers:
  ISScorer:
    batch_size: 32
    cuda: True
    resize: True
    splits: 10
  ClipScorer:
    batch_size: 2