meta_data_path: "../data/image_caption_data.json"
data_path: "../data/images"
image_key: 'image'
image_caption_key: 'caption'
id_key: 'id'
model_cache_path: '../ckpt' # Path to cache models
num_workers: 2
device: "cuda"

scorers:
  images:
    ISScorer:
        batch_size: 32
        cuda: True
        resize: True
        splits: 10
  ClipScorer:
      # data_type: image_caption
    batch_size: 2