model_cache_path: '../ckpt' # Path to cache models
num_workers: 2

data:
  image:
    meta_data_path: "../data/image_data.jsonl" # Location of the metadata
    data_path: "../data/images" # Location of the image data
    image_key: 'image' # Key corresponding to the image path (or image name) in the metadata
    id_key: 'id' # Key corresponding to the id in the metadata
    formatter: 'GenImageFormatter' # Always use GenImageFormatter for generated image data

    # Optional, for some metrics like FID and KID that require reference data, it must be specified here. For IS, default is None
    ref_meta_data_path: "../data/ref_image_data.jsonl"
    ref_data_path: "../data/images"

scorers:
  ISScorer:
    batch_size: 32
    resize: True
    splits: 10
    device: "cpu"
  FIDScorer:
    batch_size: 50
    dims: 2048
    model: https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth
    device: "cpu"
  KIDScorer:
    batch_size: 50
    dims: 2048
    model:  inception
    device: "cpu"

