
data:
  text:
    use_hf: False # Whether to use huggingface_dataset, if used, ignore the local data path below
    dataset_name: 'yahma/alpaca-cleaned'
    dataset_split: 'train'  
    name: 'default' 
    revision: null
    data_path: 'demos/text_process/fineweb_5_samples.json'  # Local data path, supports json, jsonl, parquet formats
    formatter: "TextFormatter" # Data loader type

    keys: 'text' # Key name to be processed, for sft data, it can be specified as ['instruction','input','output']

processors:
  RemoveExtraSpacesRefiner: {}
  CCNetDeduplicator: 
    bit_length: 64 # should be a multiple of 8
  NgramFilter:
    min_score: 0.99
    max_score: 1.0
    scorer_args:
      ngrams: 5