model_cache_path: '../ckpt' # Path to cache models
num_workers: 2
dependencies: [video]
save_path: './example.jsonl'
data:
  video_caption:
    meta_data_path: 'configs/process/videocap5data.json' 
    data_path: '/mnt/petrelfs/mengzimo/videodataset/vatex/videos/'
    formatter: 'VideoCaptionFormatter'  # Formatter for video-caption evaluation

processors:
  EMScoreFilter:
    min_score: 0.3
    max_score: 1.0
    scorer_args:
      batch_size: 16
      num_workers: 4
  PACScoreFilter:
    min_score: 0.3
    max_score: 1.0
    scorer_args:
      batch_size: 16
      num_workers: 4
      model_path: ./models/clip_ViT-B-32.pth
